version: "3"
services:
    db:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./db_data:/var/lib/postgresql/db_data
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin